[project]
name = "rainraingoaway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "keras>=3.14.1",
    "matplotlib>=3.10.9",
    "pandas>=3.0.3",
    "pillow>=12.2.0",
    "pyproj>=3.7.2",
    "requests>=2.34.2",
    "scipy>=1.17.1",
    "shapely>=2.1.2",
    "tensorboard>=2.20.0",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
    "python-telegram-bot>=22.7",
    "requests>=2.33.1",
]
